### ISSUE TITLE
Initialisation of voice in custom example might be incorrect?

### ISSUE THREAD

**Issue by diyelectromusic** [MajicDesigns/MD_YM2413#1]
With regards to the following line of code:

https://github.com/MajicDesigns/MD_YM2413/blob/d855d93bea92c00cd741319d0f480420cc26ab60/examples/MD_YM2413_Custom/MD_YM2413_Custom.ino#L151

I wonder if it is supposed to be: midiInstruments[0] as the parameter?

Thanks for this library.  I've been using it to understand how the YM2413 works :)

Kevin

**Comment by MajicDesigns** [comment]
You are correct. Fixed and released as v1.0.1.
