### ISSUE TITLE
Wrong value for crystal frequency

### ISSUE THREAD

**Issue by jpelletier** [MajicDesigns/MD_YM2413#3]
In the file MD_YM2413_lib.h at line 27, the define for the crystal frequency should be 3579545 which is a common TV color frequency. It's the value mentioned in the specs of the YM2413.

#define CLOCK_HZ  3597945UL

**Comment by MajicDesigns** [comment]
You are, of course, correct. This has been in the code from the very beginning so well done for spotting the extra '9'. I'll correct and reissue as version 1.1.0
